cd /data/rke_group/Herwig_Tune/out/0000
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0001
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0002
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0003
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0004
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0005
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0006
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0007
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0008
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0009
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0010
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0011
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0012
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0013
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0014
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0015
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0016
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0017
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0018
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0019
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0020
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0021
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0022
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0023
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0024
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0025
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0026
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0027
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0028
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0029
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0030
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0031
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0032
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0033
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0034
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0035
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0036
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0037
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0038
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0039
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0040
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0041
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0042
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0043
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0044
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0045
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0046
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0047
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0048
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0049
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0050
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0051
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0052
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0053
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0054
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0055
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0056
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0057
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0058
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0059
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0060
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0061
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0062
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0063
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0064
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0065
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0066
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0067
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0068
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0069
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0070
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0071
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0072
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0073
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0074
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0075
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0076
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0077
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0078
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0079
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0080
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0081
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0082
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0083
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0084
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0085
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0086
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0087
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0088
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0089
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0090
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0091
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0092
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0093
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0094
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0095
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0096
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0097
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0098
sbatch slurmrun.slurm
cd /data/rke_group/Herwig_Tune/out/0099
sbatch slurmrun.slurm
